name: docker image update

on:
  workflow_run:
    workflows: [Build]
    branches: [master]
    types: [completed]

jobs:
  main:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, windows-2022]
        include:
        - os: ubuntu-latest
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
          file: linux.Dockerfile
          tags: latest
          multiPlatform: true

        - os: windows-2022
          platforms: windows/amd64
          file: windows.Dockerfile
          tags: windows-latest
          multiPlatform: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and push
        id: docker_build
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          multiPlatform: ${{ matrix.multiPlatform }}
          registry: docker.io

          dockerfile: ${{ matrix.file }}
          image: biosmarcel/scribble.rs
          platform: ${{ matrix.platforms }}
          tags:  ${{ matrix.tags }}

          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
