name: Publish release

on:
  workflow_run:
    workflows: [Build]
    branches: [v**]
    types: [completed]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    # Kinda bad since it might release on any branch starting with v, but it'll do for now.
    # Tag filtering in "on:" doesn't work, since the inital build trigger gets lost.
    # github.ref is therefore also being reset to "refs/head/master".
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download linux artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: test-and-build.yml
          name: scribblers-linux-x64

      - name: Download macos artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: test-and-build.yml
          name: scribblers-macos-x64

      - name: Download windows artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: test-and-build.yml
          name: scribblers-x64.exe

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.workflow_run.head_branch }}
          tag_name: ${{ github.event.workflow_run.head_branch }}
          files: |
            scribblers-linux-x64
            scribblers-macos-x64
            scribblers-x64.exe
